//! Build script of the Setun-70 emulator: generates the syllable
//! configuration layer (`src/syllable_table_generated.rs`) — 729 entries
//! with the operational flags and ready-made mnemonics. This is an
//! intermediate configuration layer OF THE EMULATOR, complementing the
//! analemma core's table (which stays architecture-neutral); consumers
//! look names up instead of decoding syllables at run time.

use std::env;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;

const BAS_NAMES: [&str; 27] = [
    "LST", "COT", "XNN", "E-1", "E=0", "E+1", "T-E", "E=T", "T+E",
    "CLT", "CET", "CGT", "T=C", "R=T", "C=T", "T=W", "YFT", "W=S",
    "SMT", "Y=T", "SAT", "S-T", "TDN", "S+T", "LBT", "L*T", "LHT",
];
const SPEC_NAMES: [&str; 27] = [
    "COPYG1", "COPYG2", "COPYG3", "COPYF1", "COPYF2", "COPYF3",
    "LOADQ1", "LOADQ2", "LOADQ3", "COPYP", "EXCHP", "LOADP",
    "COPYMC", "RETNMC", "LOADMC", "LOADH1", "LOADH2", "LOADH3",
    "LOADU1", "LOADU2", "LOADU3", "LOADF1", "LOADF2", "LOADF3",
    "LOADG1", "LOADG2", "LOADG3",
];

fn value_to_trits(v: i16) -> [i8; 6] {
    let mut trits = [0i8; 6];
    let mut x = v;
    for i in 0..6 {
        let rem = x.rem_euclid(3) as i8;
        trits[i] = if rem == 2 { -1 } else { rem };
        x = ((x - trits[i] as i16) / 3) as i16;
    }
    trits
}

fn field_msb(t: &[i8; 6], from: usize) -> i8 {
    // 4-trit MSB-first field starting at `from`.
    t[from] * 27 + t[from + 1] * 9 + t[from + 2] * 3 + t[from + 3]
}

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out = Path::new(&manifest).join("src/syllable_table_generated.rs");
    let mut f = BufWriter::new(File::create(&out).unwrap());

    writeln!(f, "// Auto-generated by build.rs. Do not edit.").unwrap();
    writeln!(f, "// Syllable configuration layer of the emulator (§4 names),").unwrap();
    writeln!(f, "// complementing the architecture-neutral analemma table.").unwrap();
    writeln!(f).unwrap();
    writeln!(f, "/// Decoded syllable info: flags plus the ready-made name.").unwrap();
    writeln!(f, "#[derive(Clone, Copy, Debug)]").unwrap();
    writeln!(f, "pub struct SyllableInfo {{").unwrap();
    writeln!(f, "    /// k1 = 0 and k2 = 0.").unwrap();
    writeln!(f, "    pub is_op_syllable: bool,").unwrap();
    writeln!(f, "    /// k3 (−1 macro, 0 basic, +1 spec); 0 for address syllables.").unwrap();
    writeln!(f, "    pub op_group: i8,").unwrap();
    writeln!(f, "    /// ko (−13..=13) for operational syllables; 0 otherwise.").unwrap();
    writeln!(f, "    pub op_code: i8,").unwrap();
    writeln!(f, "    /// Mnemonic for operational syllables, `Ref<len> h[<sym>]@<ka>`").unwrap();
    writeln!(f, "    /// for address syllables.").unwrap();
    writeln!(f, "    pub mnemonic: &'static str,").unwrap();
    writeln!(f, "}}").unwrap();
    writeln!(f).unwrap();
    writeln!(f, "pub static SYLLABLES: [SyllableInfo; 729] = [").unwrap();

    for v in -364i16..=364 {
        let t = value_to_trits(v);
        let is_op = t[0] == 0 && t[1] == 0;
        let (group, code, name): (i8, i8, String) = if is_op {
            let k3 = t[2];
            let ko = t[3] * 9 + t[4] * 3 + t[5];
            let idx = (ko + 13) as usize;
            let name = match k3 {
                -1 => format!("MACRO @{}", field_msb(&t, 2)),
                0 => BAS_NAMES[idx].to_string(),
                _ => SPEC_NAMES[idx].to_string(),
            };
            (k3, ko, name)
        } else {
            let len = t[0] + 2;
            let sym = match t[1] { -1 => "-", 0 => "0", _ => "+" };
            (0, 0, format!("Ref{} h[{}]@{}", len, sym, field_msb(&t, 2)))
        };
        writeln!(
            f,
            "    SyllableInfo {{ is_op_syllable: {}, op_group: {}, op_code: {}, mnemonic: {:?} }},",
            is_op, group, code, name
        ).unwrap();
    }
    writeln!(f, "];").unwrap();
    writeln!(f).unwrap();
    writeln!(f, "#[inline(always)]").unwrap();
    writeln!(f, "pub fn info_by_value(value: i16) -> Option<&'static SyllableInfo> {{").unwrap();
    writeln!(f, "    if (-364..=364).contains(&value) {{").unwrap();
    writeln!(f, "        Some(&SYLLABLES[(value + 364) as usize])").unwrap();
    writeln!(f, "    }} else {{").unwrap();
    writeln!(f, "        None").unwrap();
    writeln!(f, "    }}").unwrap();
    writeln!(f, "}}").unwrap();
}
